name: Testing Workflow Variables

on:
  workflow_dispatch

env:
  cloud: aws-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "job1"
        run: echo "$Greeting $First_Name is using $cloud!"
        env:
          First_Name: Deepak

